### ISSUE TITLE
Tracking issue for edit package rewrite

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#778]
The rewritten `edit` package, known as `newedit` for now, has the following goals:

* High (> 90%) test coverage. This is achieved by writing testable code in the first place..

* Modular design. This is achieved by building an Elvish-agnostic core, with a set of well-defined extension points, and then adding Elvish-specific functionalities on top.

* Concurrency safety.

Non-goal:

* Additional features. The rewrite aims to achieve feature parity. New features can be added later.

**Comment by xiaq** [comment]
This is a list of editor features. I will update this comment as I progress.

- [ ] Abbreviation
- [ ] Prompt API
- [ ] Hook API
- [ ] Syntax highlighting
- [ ] Key binding API
- [ ] Completion mode
- [ ] History mode
- [ ] History listing mode
- [ ] Navigation mode
- [ ] Location mode
- [ ] Lastcmd mode

**Comment by xiaq** [comment]
OK, as I implement more stuff, some stuff makes more sense to implement in a new way that enables new features. Here is a list of new features:

- [x] Asynchronous execution of highlighter
- [ ] Asynchronous execution of listing modes

**Comment by xiaq** [comment]
Update: the new edit package is now known as `cliedit` and it is based on the general CLI package `cli`. Development has been happening in the "cliedit" branch.
